config/routes.rb
Rails.application.routes.draw do

# 会員用
devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

root to: 'public/homes#top'
get 'about' => 'public/homes#about'

scope module: :public do
    get 'users/my_page/edit' => 'users#edit'
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdraw' => 'users#withdraw'
    resources :users, only: [:show, :update, :destroy] do
      member do
        get :likes
      end
    end
    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resource :likes, only: [:create, :destroy]
    resources :comments,  only: [:create, :destroy]
  end
  get '/search' => 'searches#search'
end

#ゲストログイン
devise_scope :user do
    post '/users/guest_sign_in' => 'public/sessions#guest_sign_in'
  end

# 管理者用
devise_for :admin, skip: [:registrations, :passwords], controllers: {
sessions: "admin/sessions"
}

namespace :admin do
  resources :users, only: [:index, :show, :edit, :update]
  resources :genres, only: [:index, :edit, :create, :update]
  resources :posts, only: [:index, :create, :new, :show, :edit, :update, :destroy] do
    resources :comments,  only: [:destroy]
  end
  get '/search' => 'searches#search'
end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :genrename, uniqueness: true, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
    @genre = Genre.new
    @genres = Genre.all.page(params[:page]).per(4)
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.page(params[:page])
      render :index
    end
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
private
def genre_params
    params.require(:genre).permit(:genrename)
end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/_genre_search.html.erb
<div class="field">
  <%= form_with url: posts_path, local: true, method: :get do |f| %>
    <%= f.select :genre_id, Genre.pluck(:genrename, :id), {}, {class: 'form-control-sm col-lg-2'}%> <button class="btn btn-secondary btn-circle btn-circle-sm m-1"><i class="fa fa-search"></i></button>
      <% end %>
</div>

app/views/admin/genres/edit.html.erb
<div class="container col-12">
  <div class="mt-4">
    <h4 class="text-center bg-light"><span style="background-color: gainsboro">ジャンル編集</span></h4>
  </div>
  <div class="text-center mt-5 mb-5">
    <%= render "public/shared/error_messages", resource: @genre %>
      <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
        <div class="form-check-inline">
          <%= f.label :"ジャンル名" %>
        </div>
        <div class="form-check-inline">
          <%= f.text_field :genrename, class: 'form-control genre_name' %>
        </div>
        <div class="form-check-inline">
          <%= f.submit "変更を保存", class:"btn btn-primary" %>
        </div>
        <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container col-12">
  <div class="row">
    <div class="col">
      <div class="mt-4">
        <h4 class="text-center bg-light"><span style="background-color: gainsboro">ジャンル一覧・追加</span></h4>
      </div>
    </div>
  </div>
  <div class="container my-5">
    <div class="row">
      <div class="col">
        <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
          <%= f.label :"ジャンル名" %>
            <%= f.text_field :genrename %>
              <%= f.submit "新規登録", class:"btn btn-primary" %>
                <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-5 mt-3">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>ジャンル</th>
              <th colspan="1"></th>
            </tr>
          </thead>
          <tbody>
            <% @genres.each do |genre| %>
              <tr>
                <td>
                  <%= genre.genrename %>
                </td>
                <td>
                  <%= link_to "編集する", edit_admin_genre_path(genre), class:"btn btn-primary" %>
                </td>
              </tr>
              <% end %>
                <%= paginate @genres %>
          </tbody>
        </table>
      </div>
    </div>
  </div>