config/routes.rb
Rails.application.routes.draw do

# 会員用
devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

root to: 'public/homes#top'
get 'about' => 'public/homes#about'

scope module: :public do
    get 'users/my_page/edit' => 'users#edit'
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdraw' => 'users#withdraw'
    resources :users, only: [:show, :update, :destroy] do
      member do
        get :likes
      end
    end
    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resource :likes, only: [:create, :destroy]
    resources :comments,  only: [:create, :destroy]
  end
  get '/search' => 'searches#search'
end

#ゲストログイン
devise_scope :user do
    post '/users/guest_sign_in' => 'public/sessions#guest_sign_in'
  end

# 管理者用
devise_for :admin, skip: [:registrations, :passwords], controllers: {
sessions: "admin/sessions"
}

namespace :admin do
  resources :users, only: [:index, :show, :edit, :update]
  resources :genres, only: [:index, :edit, :create, :update]
  resources :posts, only: [:index, :create, :new, :show, :edit, :update, :destroy] do
    resources :comments,  only: [:destroy]
  end
  get '/search' => 'searches#search'
end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  
  validates :title, presence: true
  validates :artist, presence: true
  
  belongs_to :user
  belongs_to :genre, optional: true
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  has_one_attached :image
  
  def get_image
    if image.attached?
      image
    else
      'onpu.jpg'
    end
  end
  
  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
     if @post.save!
       redirect_to posts_path
     else
       render :new
     end
  end

  def index
    @genres = Genre.page(params[:page])
    if params[:genre_id].present?
      @genre = Genre.find(params[:genre_id])
      @posts = @genre.posts.order('created_at DESC').page(params[:page]).per(8)
    else
      @posts = Post.order('created_at DESC').page(params[:page]).per(8)
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.page(params[:page]).per(3)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "編集を適用しました"
      redirect_to admin_post_path
    else
      render :edit
    end
  end
  
  def destroy
    if @post = Post.find(params[:id]).destroy
      flash[:notice] = "投稿を削除しました"
      redirect_to admin_posts_path
    else
      redirect_to "/"
    end
  end

  private
   def post_params
     params.require(:post).permit(:title, :artist, :content, :genre_id, :image)
   end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/edit.html.erb
<div class="container col-12">
  <h4 class="text-center bg-light"><span style="background-color: gainsboro">投稿編集</span></h4>
  <div class="container my-5">
    <div class="text-center">
      <div class="row g-3 d-flex justify-content-center">
        <%= form_with class: "col-md-8", model: @post, url: admin_post_path, method: :patch do |f| %>
          <div class="row mb-3">
            <%= f.label :image,"写真", class: "col-md-3 col-form-label" %>
              <div class="col-lg-3">
                <%= f.file_field :image, placeholder: "写真", accept: "image/*" %>
              </div>
          </div>
          <div class="row mb-3">
            <%= f.label "曲名", class: "col-md-3 col-form-label" %>
              <%= f.text_field :title, class: "col-md-5 form-control post_title" %>
          </div>
          <div class="row mb-3">
            <%= f.label "アーティスト", class: "col-md-3 col-form-label" %>
              <%= f.text_field :artist, class: "col-md-5 form-control post_artist" %>
          </div>
          <div class="row mb-3">
            <%= f.label "ジャンル", class: "col-md-3 col-form-label" %>
              <div class="w-25">
                <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :genrename) %>
              </div>
          </div>
          <div class="row mb-3">
            <%= f.label "ひとこと", class: "col-md-3 col-form-label" %>
              <%= f.text_area :content, class: "col-md-5 form-control post_content" %>
          </div>
          <div class="row">
            <div class="col-lg-3 mt-4 offset-lg-3 text-center">
              <%= f.submit "変更", style: 'width:150px', class: "btn btn-outline-success" %>
            </div>
            <div class="col-lg-3 mt-4 text-center">
              <%= link_to "削除する", admin_post_path(params[:id]), style: 'width:150px', class: "btn btn-outline-danger", method: :delete, data: { confirm: '本当に削除しますか？' } %>
            </div>
          </div>
      </div>
      <% end %>
    </div>

app/views/admin/posts/index.html.erb
<% if flash[:notice] %>
  <div class="container">
    <div class="row mb-3">
      <div class="col p-0 alert alert-success p-0 border-0">
        <h5 class="text-center">
          <%= flash[:notice] %>
        </h5>
      </div>
    </div>
  </div>
  <% end %>
    <div class="container my-5">
      <div class="contents-title text-center">
        <h3>MUSIC</h3>
        <div class="container my-5">
          <div class="row">
            <% @posts.each do |post| %>
              <div class="col-md-3 mb-3">
                <div class="card">
                  <%= link_to admin_post_path(post) do %>
                    <%= image_tag post.get_image, class: 'card-img-top post-index-card-img' %>
                      <% end %>
                        <div class="card-body">
                          <h5 class="card-title">
                            <%= post.title.truncate(10) %>
                          </h5>
                          <div class="card-text">
                            <%= post.artist %>
                              <div><i class="fas fa-user"></i>
                                <%= link_to post.user.name,admin_user_path(post.user) %>
                              </div>
                          </div>
                        </div>
                </div>
              </div>
              <% end %>
                <%= paginate @posts %>
          </div>
        </div>

app/views/admin/posts/show.html.erb
<% if flash[:notice] %>
  <div class="container">
    <div class="row mb-3">
      <div class="col p-0 alert alert-success p-0 border-0">
        <h5 class="text-center">
          <%= flash[:notice] %>
        </h5>
      </div>
    </div>
  </div>
  <% end %>
    <section class="container mb-5">
      <div class="col-2 ml-auto">
        <%= link_to edit_admin_post_path, class: "btn btn-outline-success" do %> <i class="far fa-edit"></i>
          <% end %>
      </div>
      <div class="row mb-2">
        <div class="col-lg-6">
          <%= image_tag @post.get_image, class: 'd-block mx-auto' %>
        </div>
        <div class="col-lg-6 pt-4">
          <h3 class="text-center">
            <%= @post.title %>
          </h3>
          <h4 class="text-center">
            <%= @post.artist %>
          </h4>
          <h4 class="text-center">
            <%= @post.genre.genrename %>
          </h4>
          <p class="text-center">
            <%= @post.content %>
          </p>
          <p class="text-center">
            <%= @post.created_at.strftime('%Y/%m/%d') %>
          </p>
          <div class="container my-5">
            <% @comments.each do |comment| %>
              <div class="text-center"> <span class="font-weight-bold"><%= comment.user.name %></span> <small class="text-black-50">
        (<%= comment.created_at.strftime('%Y/%m/%d') %>)
      </small> <small>
            <%= link_to admin_post_comment_path(post_id: comment.post_id, id: comment.id), method: :delete, class: 'text-black-50', data: { confirm: '削除しますか？' } do %>
             <i class="fas fa-trash-alt"></i>
            <% end %>
          </small>
                <%= simple_format(comment.body) %>
                  <hr class="hr"> </div>
              <%= paginate @comments %>
                <% end %>
          </div>
        </div>
      </div>
      </div>
      </div>
    </section>