config/routes.rb
Rails.application.routes.draw do

# 会員用
devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

root to: 'public/homes#top'
get 'about' => 'public/homes#about'

scope module: :public do
    get 'users/my_page/edit' => 'users#edit'
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdraw' => 'users#withdraw'
    resources :users, only: [:show, :update, :destroy] do
      member do
        get :likes
      end
    end
    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resource :likes, only: [:create, :destroy]
    resources :comments,  only: [:create, :destroy]
  end
  get '/search' => 'searches#search'
end

#ゲストログイン
devise_scope :user do
    post '/users/guest_sign_in' => 'public/sessions#guest_sign_in'
  end

# 管理者用
devise_for :admin, skip: [:registrations, :passwords], controllers: {
sessions: "admin/sessions"
}

namespace :admin do
  resources :users, only: [:index, :show, :edit, :update]
  resources :genres, only: [:index, :edit, :create, :update]
  resources :posts, only: [:index, :create, :new, :show, :edit, :update, :destroy] do
    resources :comments,  only: [:destroy]
  end
  get '/search' => 'searches#search'
end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true
  validates :email, presence: true
         
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
  
  #ゲストログイン
  def self.guest
    find_or_create_by!(email: 'guest@email.com') do |user|
    user.password = SecureRandom.urlsafe_base64
    user.name = 'ゲスト'
    end
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index
    @users = User.page(params[:page]).per(5)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order('created_at DESC').page(params[:page]).per(8)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "会員情報を変更しました"
      redirect_to admin_user_path(params[:id])
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :is_deleted, :profile_image)
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row mb-3">
    <div class="col p-0 alert alert-warning p-0 border-0">
      <% if @user.errors.any? %>
        <h5 class="text-center"><%= @user.errors.size %>件のエラーが発生しました</h5>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <h6 class="text-center"><li><%= message %></li></h6>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

<div class="container col-12">
  <h4 class="text-center"><span style="background-color: gainsboro"><%= @user.name %>さんの会員情報編集</span></h1>

  <div class="row my-5">
    <div class="col-md-6 mx-auto">
  <%= form_with model: @user, url: admin_user_path, method: :patch do |f| %>
    <div class="form-group">
      <div class="row mt-4">
        <div class="col-lg-4">会員ID</div>
        <div class="col-lg-8"><%= @user.id %></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-4"><%= f.label :profile_image,"プロフィール画像" %></div>
        <div class="col-lg-8"><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-4"><%= f.label :name,"氏名" %></div>
        <div class="col-lg-8"><%= f.text_field :name, autofocus: true, class: "form-control border-dark" %></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-4"><%= f.label :email,"メールアドレス" %></div>
        <div class="col-lg-8"><%= f.text_field :email, class: "form-control border-dark" %></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-4"><%= f.label :is_deleted,"会員ステータス" %></div>
        <div class="col-lg-8">
          <%= f.radio_button :is_deleted, :false %>
          <%= f.label :is_deleted, "有効", value: false %>
          　<%= f.radio_button :is_deleted, :true %>
          <%= f.label :is_deleted, "退会", value: true %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="row offset-md-1">
        <div class="col-lg-2"></div>
        <div class="col-lg-10 text-center"><%= f.submit "変更を保存", style: 'width:150px', class: "btn btn-outline-success" %></div>
      </div>
    </div>
  <% end %>
  </div>
</div>
</div>

app/views/admin/users/index.html.erb
<div class="container col-12">
  <div class="mt-4">
  <h4 class="text-center bg-light"><span style="background-color: gainsboro">会員一覧</span></h4>
  </div>
  <div class="row my-5">
    <div class="col-md-10 mx-auto">
        <table class='table'>
          <thead>
            <tr>
              <th></th>
              <th>ユーザーネーム</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= image_tag user.get_profile_image(100,100) %></td>
                <td><%= link_to user.name, admin_user_path(user.id)  %></td>
                <td><%= user.email %></td>
                <td>
                  <% if user.is_deleted == false %>
                    <b class="text-success">有効</b>
                  <% else %>
                    <b class="text-black-50">退会</b>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<% if flash[:notice] %>
  <div class="container">
    <div class="row mb-3">
      <div class="col p-0 alert alert-success p-0 border-0">
        <h5 class="text-center"><%= flash[:notice] %></h5>
      </div>
    </div>
  </div>
<% end %>


<div class="container my-5">
   <div class="contents-title text-center">
     <h3><%= @user.name %>さんの会員ページ</h3>
      <div class="container my-5">
        <div class="text-center">
          <%= image_tag @user.get_profile_image(100,100) %>
            <h5><%= @user.name %></h5>
        </div>
      </div>

        <div class="row">
        <div class="text-center">
          <%= link_to edit_admin_user_path, style: 'width:150px', class: "btn btn-outline-success" do %>
             <i class="fas fa-user-cog"></i>
          <% end %>
        </div>

<div class="container my-5">
<div class="row">
  <% @posts.each do |post| %>
    <div class="col-md-3 mb-3">
      <div class="card">
        <%= link_to admin_post_path(post) do %>
          <%= image_tag post.get_image, class: 'card-img-top post-index-card-img' %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= post.title.truncate(10) %></h5>
          <div class="card-text">
            <%= post.artist %>
          </div>
        </div>
        <div class="card-footer text-right">
          <i class="fas fa-comment"></i><%= link_to "#{post.comments.count}", admin_post_path(post), class:"text-dark" %>
        </div>
      </div>
    </div>
  <% end %>

  <%= paginate @posts %>
</div>