config/routes.rb
Rails.application.routes.draw do

# 会員用
devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

root to: 'public/homes#top'
get 'about' => 'public/homes#about'

scope module: :public do
    get 'users/my_page/edit' => 'users#edit'
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdraw' => 'users#withdraw'
    resources :users, only: [:show, :update, :destroy] do
      member do
        get :likes
      end
    end
    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resource :likes, only: [:create, :destroy]
    resources :comments,  only: [:create, :destroy]
  end
  get '/search' => 'searches#search'
end

#ゲストログイン
devise_scope :user do
    post '/users/guest_sign_in' => 'public/sessions#guest_sign_in'
  end

# 管理者用
devise_for :admin, skip: [:registrations, :passwords], controllers: {
sessions: "admin/sessions"
}

namespace :admin do
  resources :users, only: [:index, :show, :edit, :update]
  resources :genres, only: [:index, :edit, :create, :update]
  resources :posts, only: [:index, :create, :new, :show, :edit, :update, :destroy] do
    resources :comments,  only: [:destroy]
  end
  get '/search' => 'searches#search'
end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :genrename, uniqueness: true, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/post.rb
class Post < ApplicationRecord
  
  validates :title, presence: true
  validates :artist, presence: true
  
  belongs_to :user
  belongs_to :genre, optional: true
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  has_one_attached :image
  
  def get_image
    if image.attached?
      image
    else
      'onpu.jpg'
    end
  end
  
  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true
  validates :email, presence: true
         
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
  
  #ゲストログイン
  def self.guest
    find_or_create_by!(email: 'guest@email.com') do |user|
    user.password = SecureRandom.urlsafe_base64
    user.name = 'ゲスト'
    end
  end
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
    @genre = Genre.new
    @genres = Genre.all.page(params[:page]).per(4)
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.page(params[:page])
      render :index
    end
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
private
def genre_params
    params.require(:genre).permit(:genrename)
end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
     if @post.save!
       redirect_to posts_path
     else
       render :new
     end
  end

  def index
    @genres = Genre.page(params[:page])
    if params[:genre_id].present?
      @genre = Genre.find(params[:genre_id])
      @posts = @genre.posts.order('created_at DESC').page(params[:page]).per(8)
    else
      @posts = Post.order('created_at DESC').page(params[:page]).per(8)
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.page(params[:page]).per(3)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "編集を適用しました"
      redirect_to admin_post_path
    else
      render :edit
    end
  end
  
  def destroy
    if @post = Post.find(params[:id]).destroy
      flash[:notice] = "投稿を削除しました"
      redirect_to admin_posts_path
    else
      redirect_to "/"
    end
  end

  private
   def post_params
     params.require(:post).permit(:title, :artist, :content, :genre_id, :image)
   end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index
    @users = User.page(params[:page]).per(5)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order('created_at DESC').page(params[:page]).per(8)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "会員情報を変更しました"
      redirect_to admin_user_path(params[:id])
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :is_deleted, :profile_image)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
    <% if admin_signed_in? %>
      <%= link_to "Otokore", root_path, class:"header-title navbar-brand"%>
        <% else %>
          <%= link_to "Otokore", root_path, class:"header-title navbar-brand"%>
            <% end %> <button class="navbar-toggler mx-5" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
              <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                <ul class="navbar-nav">
                  <% if user_signed_in? %>
                    <li class="nav-item ">
                      <%= link_to "マイページ", user_path(current_user), class: 'btn btn-outline-secondary mx-3 my-1'%>
                    </li>
                    <li class="nav-item ">
                      <%= link_to "投稿一覧", posts_path, class: 'btn btn-outline-secondary mx-3 my-1'%>
                    </li>
                    <% if current_user.email != 'guest@email.com'%>
                      <li class="nav-item">
                        <%= link_to "投稿する", new_post_path, class: 'btn btn-outline-secondary mx-3 my-1'%>
                      </li>
                      <% end %>
                        <li class="nav-item">
                          <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: 'btn btn-outline-secondary mx-3 my-1'%>
                        </li>
                        <%= render partial: 'layouts/searchform' %>
                          <% elsif admin_signed_in? %>
                            <li class="nav-item">
                              <%= link_to "投稿一覧", admin_posts_path, class: 'btn btn-outline-secondary mx-3 my-1' %>
                            </li>
                            <li class="nav-item">
                              <%= link_to "会員一覧", admin_users_path,  class:'btn btn-outline-secondary mx-3 my-1'%>
                            </li>
                            <li class="nav-item">
                              <%= link_to "ジャンル一覧", admin_genres_path, class: 'btn btn-outline-secondary mx-3 my-1'%>
                            </li>
                            <li class="nav-item">
                              <%= link_to "ログアウト",destroy_admin_session_path, method: :delete,class: 'btn btn-outline-secondary mx-3 my-1'%>
                            </li>
                            <%= render partial: 'layouts/searchform' %>
                              <% else %>
                                <li class="nav-item">
                                  <%= link_to "About", about_path,class: 'btn btn-outline-secondary mx-3 my-1' %>
                                </li>
                                <li class="nav-item">
                                  <%= link_to "新規登録", new_user_registration_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
                                </li>
                                <li class="nav-item">
                                  <%= link_to "ログイン", new_user_session_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
                                </li>
                                <li class="nav-item">
                                  <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: 'btn btn-outline-secondary mx-3 my-1' %>
                                </li>
                                <% end %>
                </ul>
              </div>
  </nav>
</header>

app/views/layouts/_searchform.html.erb
<div class="row pt-2 d-none d-sm-inline">
    <div class="col text-right">
      <%= form_with url: search_path, method: :get, local: true, class:"form-inline" do |f| %>
        <%= f.text_field :word_for_search, class:"form-control", size:'20',placeholder: "キーワードを入力" %>
        <%#= f.submit "Search", class:"btn btn-outline-success" %>
        <button class="btn btn-secondary btn-circle btn-circle-sm m-1"><i class="fa fa-search"></i></button>
      <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OtoKore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  </head>

  <body>
    <div id="wrapper">

    <%= render "layouts/header"%>
    <%= yield %>
    </div>
  </body>
</html>